version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql+psycopg2://dev:Aa%4012345@database-1.c5mswemmu8to.us-west-2.rds.amazonaws.com:5432/database-1"
      DB_HOST: database-1.c5mswemmu8to.us-west-2.rds.amazonaws.com
      DB_PORT: 5432
      GEMINI_API_KEY: "GEMINI_API_KEY"
    command: >
      uvicorn app.app_server:app --host 0.0.0.0 --port ${PORT:-8080}

volumes:
  postgres_data: